name: Filter update
description: Suggest fixes or improvements to an existing filter
labels: filter-data

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new filter!
        Please take a look at our [contribution guidelines](https://letsblock.it/help/contributing) first.
        
        To suggest a new filter, [use this form](https://github.com/letsblockit/letsblockit/issues/new?template=new-filter.yaml) instead.
  - type: input
    attributes:
      label: What filter does this issue target?
      description: Copy a link to the filter's page, or it's name
    validations:
      required: true
  - type: textarea
    attributes:
      label: What changes should be made?
      description: Content not blocked? Screenshots welcome!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Did you write a uBlock filter solving this?
      description: If you already wrote a filter, copy it here as a starting point
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional notes
      description: Any additional context for this, or alternatives to discuss?
    validations:
      required: false
